### ISSUE TITLE
Does not work in Gatsby

### ISSUE THREAD

**Issue by robotmayo** [bumbag/bumbag-ui#15] opened 2020-08-06 06:08 UTC
Reproduction is simple, start a new gatsby starter project then follow the gatsby instructions on the website. Getting this error:
```
TypeError: theme.modes is undefined
useLocalStorage
node_modules/bumbag/es/utils/useLocalStorage.js:14

  11 | var _useTheme = useTheme(),
  12 |     theme = _useTheme.theme;
  13 | 
> 14 | var isEnabled = theme.modes.enableLocalStorage;
  15 | var get = useCallback(function (key) {
  16 |   if (!isEnabled) return;
  17 | 
```
- Bumbag 1.0.2
- Bumbag Gatsby Plugin 1.02
- Gatsby 2.24.30

**Comment by jxom** [comment] 2020-08-06 06:48
Heya! I tried to reproduce your example, but I couldn't get that error to pop up.

Did you make sure to include your `<BumbagProvider>` in your `gatsby-browser.js` file?

I have also added a [Bumbag Gatsby Example](https://github.com/bumbag/bumbag-ui/tree/master/examples/gatsby-basic) if you wish to take a look at a working example in code.

**Comment by jxom** [comment] 2020-08-06 12:29
Closing for now.

**Closed by jxom** 2020-08-06 12:29 UTC
Labels: question

**Comment by robotmayo** [comment] 2020-08-06 16:16
@jxom Its still not working as of 1.0.4. Heres a repo: https://github.com/robotmayo/bumbag-repro

**Comment by jxom** [comment] 2020-08-07 00:34
Hmm, looks like there were dependency issues with npm... Can you try update to `1.0.8` and try again? thanks.

**Comment by robotmayo** [comment] 2020-08-07 00:49
It appears to be working now as of at least `1.0.8`. Thank you.

**Comment by jxom** [comment] 2020-08-07 01:00
Woo!
