### ISSUE TITLE
The last option of the horizontal RadioGroup is not aligned

### ISSUE THREAD

**Issue by firede** [bumbag/bumbag-ui#51] opened 2020-08-25 10:43 UTC
**Describe the bug**

The last option of the horizontal `RadioGroup` is not aligned.

**To Reproduce**

see [docs](https://bumbag.style/form/radio-group/#horizontal-group)

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/157338/91165019-92f98b80-e702-11ea-9ac5-a2b9fa8220ad.png)

**Device information (please complete the following information):**

-   Device: Macbook Pro
-   OS, version: macOS 10.15.6
-   Browser, version: Chrome 84.0.4147.135
-   Bumbag version: v1.1.8

-   [What's My Browser URL](https://www.whatsmybrowser.org/):

**Additional context**

**Comment by DarkSmile92** [comment] 2020-08-25 13:04
I tried to reproduce this on the playground and on a plain create-react-app project.
Without any success.
It seems like this is only occuring in the docs because of this css rule:
```css
.css-1n8wpf9:not(:last-child) {
    margin-bottom: 6.67188px;
}
```
![image](https://user-images.githubusercontent.com/10928916/91177549-2cfe0b80-e6e4-11ea-9def-af096b863cb6.png)

Can't find where this rule is coming from @jxom 

@firede did you see this issue just in the docs or also in a project of yours?

**Comment by jxom** [comment] 2020-08-25 13:13
This should be fixed now on the latest version

**Closed by jxom** 2020-08-25 13:13 UTC
Labels: bug
